Feature: strip version prefix
malukenho/mcbumpface pull request #25
Opened 2020-01-24 11:52 UTC by boesing

This relates to #23

2020-01-24 11:56 UTC, boesing commented
Mhm, any suggestions on how to pass the slevomat coding style for PHP 7.4?

2020-01-24 13:32 UTC, Slamdunk commented
Add an environment variable for the lowest step, and only run phpcs if the variable is set, see for example https://github.com/laminas/laminas-validator/blob/master/.travis.yml#L22

Coding standard should run in the lowest supported language version only

2020-01-24 16:51 UTC, boesing commented
Yah I know that but wasnt enabled here and I dont think that should be part of this PR. Maybe I create another PR on monday.

2020-01-24 17:03 UTC, Slamdunk commented
It's a small library, just do it here, to me

2020-01-24 18:19 UTC, boesing commented
@malukenho tell me 🤷🏼‍♂️
Im fine with both 

- 2nd PR
- in here 

And: are you fine with this Feature.

2020-01-26 06:24 UTC, Slamdunk requested changes

2020-01-26 06:24 UTC, Slamdunk commented on test/BumpIntoTest.php
> +            'options' => ['stripVersionPrefixes' => true],
We should add this to readme somehow

2020-01-27 12:41 UTC, malukenho commented
I'm all fine with doing multiples SMALL changes in a single PR if they are committed separately, so it is okay.

It looks nice! We just need to address [https://github.com/malukenho/mcbumpface/pull/25#discussion_r370976506](this) comment and merge it 👍

2020-01-27 14:39 UTC, boesing commented
I've added configuration section to the README file

https://github.com/boesing/mcbumpface/tree/feature/strip-version-prefixes#configuration-optional

2020-01-27 15:37 UTC, Slamdunk approved these changes

2020-01-27 16:53 UTC, merged

2020-01-27 16:54 UTC, malukenho commented
Thank you very much @boesing 🎉

2020-01-29 11:47 UTC, Slamdunk commented
@malukenho may we tag this with a new minor, like `1.1.0`?

2020-01-29 14:01 UTC, malukenho commented
Ofc! I'll do it at the end of the day.

2020-01-29 14:01 UTC, Slamdunk commented
Thank you very much :beers:

2020-01-29 18:10 UTC, malukenho commented
Just FYI `1.1.0` released @Slamdunk 🎉